### ISSUE TITLE
email validation

### ISSUE THREAD

**Issue by anakistudio** [SPOTBusinessSystems/SPOT.CustomerConnect.Template#1]
The CustomerConnect.Util.Validate.EmailAddress function is too restrictive on the domain.

It doesn't allow dash, which is a valid character in a domain, and newer TLDs exist now that are 24 characters long.

**Comment by tlewis17** [comment]
That is true. It also appears like it will have issues with email addresses that contain subdomains. I'm doing some investigation to find a better one. 

I have a new one I may use:
^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,}

That should cover almost any case, even some invalid emails. I'm not worried about accepting some invalid emails but I want to avoid denying emails that are in fact valid.

**Comment by anakistudio** [comment]
Doesn't the "." symbol mean 'any symbol', and should be escaped like 
^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,}

**Comment by tlewis17** [comment]
That looks like the same one that I already put in in my last comment. That is the one I have added to the defaults.

**Comment by anakistudio** [comment]
Sorry, didn't notice that it ate my backslashes, should've read:
^[A-Za-z0-9\._%+-]+@[A-Za-z0-9\.-]+\.[A-Za-z]{2,}

**Comment by tlewis17** [comment]
You are correct. I have made the adjustment.
